---
title: Project Review Template 
author: Andrew 
date: date-modified
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Factors associated with obesity

Name of project author(s): Hu Xueyan

Name of project reviewer: Andrew Ruiz

# Instructions

Write your comments and feedback below for each section/component of the project. The goal should be to help the author improve their project. Make comments as constructive and actionable as possible. You can provide both criticism and praise.

For each component, pick one summary statement by deleting the ones that do not apply and keeping only the one that you think most closely summarizes a given component.

Make sure your final document compiles/renders into a readable, well-formatted html document.

Delete any sections/text of this template that are not part of your final review document. (Including these instructions.)

# Specific project content evaluation

Evaluate the different parts of the project by filling in the sections below.

## Background, Context and Motivation

How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

The background provides appropriate amount of information on the topic. This section could benefit from an explanation of how these models might have an impact on incidence, interventions, etc of obesity.

Citations appear to be formated correctly. However, in paragraph 2 of section 2.1, the text mentions stats from the CDC, but there is not a citation for these.

It might also be worth noting, either here or in the limitations, that BMI can be misleading and is not a perfect indicator of obesity.

The term KOL is used in this section, but it is not defined, as far as I can see.

### Summary assessment (PICK ONE, DELETE THE OTHERS)

-   some contextualization and motivation

## Question description

How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?

### Feedback and Comments

The question is well defined, but it also seems to evolve by the end of the paper. I would recommend re-visiting the question to ensure it covers the scope of the analysis.

### Summary assessment

-   question/hypotheses somewhat explained

## Data description

How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is?

### Feedback and Comments

A code book is available for the data. The source of the data is provided. The overall structure of the data is described.

However, this section could benefit from a better description of the dataset. How were the participants recruited? Was this a random sample? Etc.

### Summary assessment

-   source and overall structure of data somewhat explained

## Data wrangling and exploratory analysis

How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

The data wrangling process is straightforward and well described in the qmd files. It could be better described in the manuscript. Were there any records that were excluded because of missing values, etc.?

### Summary assessment

-   essentially no weaknesses in wrangling and exploratory component

## Appropriateness of Analysis

Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

The analysis appears appropriate. However, I am having trouble matching the models in the manuscript table to the models in the qmd. Consider directly referencing the names from the qmd in the manuscript.

### Summary assessment

-   defensible but not optimal analysis

-   <div>

    ## Presentation

    </div>

How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality?

### Feedback and Comments

The tables and figures were clear. I would consider omitting the bar graph of gender, I don't think it demonstrates the age any better than text.

The table in 4.3 could be improved by reformatting the 'Metric Value' column so that the numbers are not split.

### Summary assessment

-   results are very well presented

## Discussion/Conclusions

Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

I think that the reporting of results was appropriate. But the discussion of the results could be improved. What do the findings suggest? How would this inform future research?

The interactions in the models should be discussed with more detail. How did you decide which interactions to include, etc.

Additionally, a better description of the linear model would improve the discussion. Were all levels of the catgorical BMI used?

Strengths and weakness should be expanded to include how the dataset affects the interpretation. Was it a random sample? Does the different countries included in the dataset make generalization easier or harder? What affect might the interaction have on the results? Etc.

### Summary assessment

-   major parts of discussion missing or wrong
-   minor parts wrong, missing or unclear
-   strong, complete and clear discussion

## Further comments

*Add any other comments regarding the different aspects of the project here. Write anything you think can help your classmate improve their project.*

# Overall project content evaluation

Evaluate overall features of the project by filling in the sections below.

## Structure

Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

There are some files not in use that are still in the code files. There is also text in some of the used code files left over from the template.

The README files should be updated.

While the structure is uncluttered and not confusing, there is still some clean up to perform before finalizing the project.

### Summary assessment

-   mostly clear, but some confusing parts (e.g. useless files, things in the wrong folders)

-   <div>

    ## Documentation

    </div>

How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files?

### Feedback and Comments

Where the process is documented the objectives are mostly clear. However, the README files need to be updated to guide users on how to use the repository.

One more note: the qmd called exploratory-analysis should be renamed. The name currently implies it should go with the EDA folder

### Summary assessment

-   decently documented with some gaps

-   

-   <div>

    ## Reproducibility

    </div>

Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

The code ran without errors until the final exploratory-analysis file (several chunks beginning at line 155).

Chunk 9 error:

```         
Error: object 'minRMSE1' not found
```

Chunk 11 error:

Error in model.frame.default(Terms, newdata, na.action = na.action, xlev = object\$xlevels) :
factor Alcohol has new levels 4

Chunk 13:

```         
Error in all_predictors[1:i] : 
  object of type 'closure' is not subsettable
```

Chunk 14:

Error in lda.default(x, grouping, ...) :
variable 3 appears to be constant within groups

### Summary assessment

-   small parts not reproducible or required manual intervention

## Thoroughness

How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

The study design was straightforward. It was a good decision to calculate a new feature with the actual BMI. Still this category is the least developed in this rubric, but can easily be corrected the some minor adjustments.

The decision to use all seven catgories of BMI for the classification models should have been discussed and alternatives (creating 2 classes obese/not obese, for example) should have been explored.

I think the thoroughness could be improved with expanded discussion, limitations, and data source sections.

### Summary assessment

-   weak level of thoroughness

## Further comments

This was an easy-to-follow, straightforward design. The text might benefit from a review of the perspective and tone. At times it seemed like an academic paper and other times it was more of a narrative.
